- name: create folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.9.138:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: create pipelines jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipeline_jobs }}"

